---
- hosts: all
  vars_files:
    - user_list.yml
  tasks:
    - name: Add group
      group:
        name: "{{item.group}}"
        state: present
      with_items: "{{users}}"  
    - name: Add user
      user:
        name: "{{item.name}}"
        group: "{{item.group}}"
        state: present
      with_items: "{{users}}"
...      
