---
- hosts: all
  vars_files: 
    - user_list.yml
  tasks:
    - name: Create group
      group:
        name: "{{item.group}}"
        state: present
      with_items: "{{users}}"
    - name: Create user
      user:
        name: "{{item.name}}"
        state: present
      with_items: "{{users}}"  
...      
